### ISSUE TITLE
Using customGET with array parameter

### ISSUE THREAD

**Issue by rpungello** [mgonto/restangular#1013]
I'm having a small issue with passing an array as a parameter to the customGET function.

Basically, if I call `Restangular.all('resource').customGET('/', { 'foo[]': ['bar', 'baz'] })` the square brackets get encoded twice in the resulting URL ([ -> %5B -> %255B). This obviously causes issues with the backend processing.

However, the same concept works fine for the .get() and .getList() functions. If I pass in an array (using the [] syntax), it gets sent properly encoded.

Am I doing this right, or is there a better way (other than manually constructing the URL) to use an array as a parameter?

**Comment by grabbou** [comment]
Angular $http issue -> https://github.com/angular/angular.js/issues/3740. To be fixed in upcoming 1.4 release, should be fixed in Restangular as soon as we upgrade and they release it. For now, nothing to fix here as we are sending raw query params to $http and there's nothing we can do about the way it serialises the data for now.
