### ISSUE TITLE
inconsistent api && documentation

### ISSUE THREAD

**Issue by debris** [mgonto/restangular#1051]
after reading README.md I'm confused

[Decoupled Restangular Service](https://github.com/mgonto/restangular#decoupled-restangular-service) describes using restangular in service.

**1.** at first I setup Restangular as servie:
```javascript
// Declare factory
module.factory('users', function(Restangular) {
  return Restangular.service('users');
});
```

that works great.

**2.** then I get list of all users

```javascript
users.getList()
// GET /api/users
```
also works great!

**3.** then I want to get user from `/api/users/2`
```javascript
// first test
users.one(2).get();
// GET /api/users/2

// second test
users.get(2);
// i do get some error from which I am able to find the issue

// third test
users.one().get(2);
// GET /api/users
// not working, as expected
```

**4.** then i want to get user from `/api/users/first/second`
```javascript
// expected:
// GET /api/users/first/second

// first test
users.one('first', 'second').get()
// GET /api/users
// ???? what happend here?

// second test
users.one('first').one('second').get()
// GET /api/users/first/second
// that's correct

// third test
users.one('first').get('second')
// GET /api/users/first
// not working as expected

// fourth test
users.get('first', 'second')
// GET /api/users
// again, i would like to see some error here!
```

if I passed wrong params, I **expect** to be notified about this and I to see console errors.

**5.** just a simple POST

```javascript
users.post({hello: "1"});
// POST /api/users
// body: {}
```

works great!

**6.** post to `/api/users/first` object {hello: "1"}
```
// expected
// POST /api/users/first
// body  {hello: "1"}

users.one('first').post({hello: "1"})
// POST /api/users/first/[object%20Object]
// body: {_id: "first" }
// what happened here?

users.one('first').one('second').post({hello: "1"})
// POST /api/users/first/second/[object%20Object]
// body: {}
// what happend with body?

users.post('second', {hello: "1"})
// POST /api/users?hello=1
// body: second
// ???

users.one().post('second', {hello: "1"})
// POST /api/users/first
// body:  {hello: "1"}
// success, finally!

users.one('first', 'second').post({hello: "1"})
// POST /api/users/[object%20Object]
// body: {_id: "first" }
// it does not work :/
```

This is really inconsistent with what is described in wiki, eg:

```javascript
// This will do ONE get to /accounts/123/buildings/456/spaces/789
Restangular.one("accounts", 123).one("buildings", 456).one("spaces", 789).get()
```

After reading this, I expect, that every time, I pass some params to `one` I will get path appended by these params.

Am I missing something? What is the correct way of using restangular?

**Comment by grabbou** [comment]
Hey @debris,

Generally, in Restangular you have `Restangular methods` which are used to create URLs (like `one()`, `all()`) and `Element/Collection methods` which are used to invoke those operations by performing request and optionally passing specific parameters, like "body" in POST/PUT (`post()`) or query params in GET (`get()`). 

Afterwards, you get an access to element/collection methods which have some requirements in terms of arguments you pass but we do not handle those misuses in a graceful way and thus there's an ongoing work to improve them pretty soon.

In response to point 3

This has to work as one(route, id) accepts optional route argument and id. 

```
users.one(2).get();
```

As per documentation, get signature only accepts query parameters, and "2" is ID, not query parameter so that's what produces that error.
```
users.get(2);
```

Same as above, incorrect usage. 
```
users.one().get(2);
```

In response to 'POST' (and generally other methods as well)...

You have Collection methods and Element methods described above. Generally, they have the same name which is why you are confused.

Lets compare POST signatures

ELEMENT
> post(subElement, elementToPost, [queryParams, headers]): Does a POST and creates a subElement. Subelement is mandatory and is the nested resource. Element to post is the object to post to the server.

COLLECTION
> post(elementToPost, [queryParams, headers]): Creates a new element of this collection.

As expected, if you are operation on collection, post should just post a new element on it. If you are operating on single element, to perform post() (save it) you should use save() method. If you call post() on element, Restangular thinks you want to do something different, like invoke `/users/1/favourites` and because of that it exposes `subElement` property as its first argument.

Let's go through your example:
```js
users.one('first').post({hello: "1"})
// POST /api/users/first/[object%20Object]
// body: {_id: "first" }
- You are on element object because you used Restangular root level called "one". You forgot to specify ID which might make you confused, as normally that'd be /api/users/first/<id>/[object%20Object]. 

users.one('first').one('second').post({hello: "1"})
// POST /api/users/first/second/[object%20Object]
// body: {}
Exactly same as above.

users.post('second', {hello: "1"})
// POST /api/users?hello=1
// body: second
Collection method, first argument is body, second query parameters. The first argument from element method "subElement" is omitted, as with collections this is not needed.

users.one().post('second', {hello: "1"})
// POST /api/users/first
// body:  {hello: "1"}
Correct usage. Element and its correct signature.

users.one('first', 'second').post({hello: "1"})
// POST /api/users/[object%20Object]
// body: {_id: "first" }
Incorrect usage. Element so first argument is missing.
```

**Comment by grabbou** [comment]
Closing as it turns out that @debris is my flatmate :+1:
