### ISSUE TITLE
How can I add custom method to ALL collections by default?

### ISSUE THREAD

**Issue by iqbal-admedo** [mgonto/restangular#1288]
So I can see we can add custom methods to a specific collection using addElementTransformer, however I have to specify the 'route' each time.

However I have collections that share common methods, is there anyway to specify this so it applies to all routes by default?

I am creating all my services using the Restangular.service.

**Comment by cfey** [comment]
Hi, 
I wrote a couple of "extender" services, they only have one function which calls
```
Restangular.extendModel('route', function(model) {
    model.isAdmin = function () {
          // custom code here
    };
    model.doSomethingCool = OtherService.doSomethingCool;
});
```
The OtherService has a method "doSomethingCool" which you want to share.

If you go for JavaScript "Classes" you could even use
```
Restangular.extendModel('route', function(model) {
    angular.extend(model, ModelBaseClass);
});
```
I have to admit, I never used the second method :sweat_smile:

**Comment by daviesgeek** [comment]
Isn't that what [setOnElemRestangularized](https://github.com/mgonto/restangular#setonelemrestangularized) is for?

```js
RestangularProvider.setOnElemRestangularized(function(elem, isCollection, what, Restangular) {
  elem.addedMethod = function() {
    console.log('hey! I am an added method!')
  }
})

```

**Comment by cfey** [comment]
In the docs it says
> I favor the usage of **addElementTransformer** instead of **onElemRestangularized** whenever possible as the implementation is much cleaner.

and then in the `extendModel` doc it says
> Create custom methods for your models using Restangular.extendModel(). This is an alias for:
`Restangular.addElementTransformer(route, false, fn);`

so I assume `Restangular.extendModel` is the right way to go?

**Comment by daviesgeek** [comment]
Any of these ways will work. The OP's question was "how do I do this without specifying the route again?".

There's also not _necessarily_ a "right" way or a "wrong" way. There might be a semantically better way (as with what the docs say about `addElementTransformer ` vs. `onElemRestangularized `), but not right/wrong. Both methods are available to use; they both do the same thing; it's more of a preference. 

I personally would rather use `extendModel` because I don't have to pass in the second `false` parameter to denote whether it's a collection or not ([see docs](https://github.com/mgonto/restangular#addelementtransformer)), but that's just me.

**Comment by daviesgeek** [comment]
I'm going to close this for now. Feel free to re-open if there's still an issue.
