### ISSUE TITLE
How to convert query with withHttpConfig to customGET

### ISSUE THREAD

**Issue by essivision** [mgonto/restangular#1363]
Hi
How to convert this query

```
Restangular.one('user/export/excel').withHttpConfig({responseType: 'blob'}).get().then(function(response) {
             var url = (window.URL || window.webkitURL).createObjectURL(response);
             window.open(url,"_self");
        })
```

to

```
var _userService = Restangular.all('user');

_userService.customGET('export/excel').withHttpConfig({responseType: 'blob'}).get().then(function(response) {
             var url = (window.URL || window.webkitURL).createObjectURL(response);
             window.open(url,"_self");
        })
```

**Comment by ConcurrentHashMap** [comment]
```
var _userService = Restangular.all('user');

_userService.withHttpConfig({responseType: 'blob'}).customGET('export/excel').then(function(response) {
    var url = (window.URL || window.webkitURL).createObjectURL(response);
    window.open(url,"_self");
})
```

should work.

**Comment by essivision** [comment]
but using this log me in console
```
Resource interpreted as Document but transferred with MIME type application/vnd.ms-excel: "blob:http%3A//localhost/f3f4e1dd-db19-4a58-8a39-8e4d79908395"
```
How to fix it?

**Comment by ConcurrentHashMap** [comment]
Seems to me as this happens when trying to create the object URL inside the then() callback.

This seems to be a Chrome related problem [already mentioned multiple times on Stack Overflow](https://stackoverflow.com/questions/6587393/resource-interpreted-as-document-but-transferred-with-mime-type-application-zip). Can you paste the request and response headers of this customGET call from the network tab?

**Comment by daviesgeek** [comment]
@essivision Any update?

**Comment by bostrom** [comment]
Closing due to the nature and age of issue. Please consider the updated [issue guidelines](https://github.com/mgonto/restangular/blob/master/.github/ISSUE_TEMPLATE.md) and reopen if needed.
