### ISSUE TITLE
.put() method ignoring id param for URL build

### ISSUE THREAD

**Issue by aliriocastro** [mgonto/restangular#1421]
I have this code to reproduce what I consider an issue

``` javascript
var app = angular.module('myApp', ['restangular']);

    app.controller('MainCtrl', function ($scope, Restangular) {
    var resource = Restangular.one('customers', '123');

    resource.get().then(function(resp) {
    var result = resp;      
    });

    function getUrl() {
    resourceUrl = resource.getRestangularUrl();
    // returns /customers/123
    resultUrl = resource.getRestangularUrl();
    // returns /customers
   }

});
```

NOW, If I add the id parameter to the returned object when resource.get()

``` javascript
// HACK
result.id = '123';`
```

Result:

``` javascript
resourceUrl = resource.getRestangularUrl();
// returns /customers/123
resultUrl = resource.getRestangularUrl();
// returns /customers/123
```

Is this a normal behavior, or could be considered as an issue?

Regards,

Alirio.

**Comment by bostrom** [comment]
@aliriocastro I wrote some [unit tests](https://github.com/mgonto/restangular/pull/1455) to try to reproduce the problem and it seems that if the server doesn't respond to your `.get()` request with an object containing the id, you get an empty id in the URL from `getRestangularUrl()`. 

So let's say you request `GET /accounts/123` and the server responds with `{"name": "Account123"}`, i.e. a JSON object without id property. Now the resulting Restangularized element won't have an ID since the response object doesn't have one and the `getRestangularUrl()` method will only return `/accounts`.

The unit tests always succeed when there's an id property in the response JSON matching the request. 

Does this explain the behavior you're experiencing?
