### ISSUE TITLE
Bootstraping initial data on page load

### ISSUE THREAD

**Issue by ruimarinho** [mgonto/restangular#190]
Bootstraping initial data is a common use case to avoid fetching required resources after page load.

I was wondering if Restangular supports this or if there is any plan to do so.

**Comment by tychay** [comment]
The problem with your example:
```js
var user = Restangular.one('users', 'me');
_.extend(user, objectData);
```
is that what it does is extend the `Restangular.one()` object, but what most people will want to do is extend the `$object` returned by `Restangular.one().get()`

For instance, let's say your controller sets/uses the following:
```js
$scope.me = Restangular.one('users','me').get().$object
```
Doing the above will still make the `$http` request.

I think you can do something like:
```js
var obj_from_service = Restangular.one('users','me');

…

// preloader
Restangular.restanguarlizeElement(null,objectData);
obj_from_service.get = function() { return { $object: data }; }

…

$scope.me = obj_from_service.get().$object
```

Now the behavior with or without the preloading code will return the same result and prevent `$http` from being activated by `get()`. The differences are:

1. You've masked the get method from the `obj_from_service`, so I have no idea how that will interact if you do a `put()` then a `get()` again because I don't know how Restangular handles that
2. If you have request injectors on the `Restangular` object (for instance you're modifying `reqParams` to add an `api_key`, then the `$object` will not have them) because it looks like the constructor uses the `RestangularProvider` only.

There's probably a way to fix this if I understood promises better (my thinking is I could just set the `$object` property and resolve the promise), but I only learned AngularJS a week ago and Restangular two days ago and I'm a back-end developer. :-( So any suggestions on improving this would be greatly appreciated.

**Comment by tychay** [comment]
To answer part of my own discussion, apparently I have a misunderstanding of `Restangular(proxy).get()` and `restangularized-object.get()`. So you don't want to mask it. Instead what you want to do is use a factory/service to return the `$object` unless it is preloaded and then return the restangularized version of whatever is preloaded.
