### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by roylee0704** [mgonto/restangular#232]
Is it possible to encode the URL before fire up the request?

e.g:

> $scope.user.getList('cars'); //would fires users/123/cars.

Let say, the user's id contains characters like: `~!@#$&*()=:/,;?+'`, and I want to encode before sending.  E.g:`roy#01`.

**Comment by RichardBradley** [comment]
I think this is a bug, and `restangular` should url-encode supplied entity IDs before using them to construct REST urls.

You said:

> $http encodes the Request Parameters as tey need to be encoded. It doesn't encode the rest of the URL and for a good reason. Maybe you actually want to go to a URL with a # which is entirely possible.

... but this is not comparable, because the argument to `$http` is a URL, whereas the argument to `restangular` functions like `getList` is an entity ID. It is correct for angularJS to not url-encode a URL typed argument, as that would result in double-encoding, as you point out. However, it is incorrect for restangular to not URL encode a String value when using it in a URL.

**Comment by RichardBradley** [comment]
The bugged line looks to be at https://github.com/mgonto/restangular/blob/de8a48bf4c13587b9ba5a975b5be1b0c3dd7a4bd/src/restangular.js#L663 :

    elemUrl += '/' + ids.join(',');

When adding a string value to a URL as a path segment, it is a type error to not url-encode the string value.

**Comment by RichardBradley** [comment]
This bug was fixed at https://github.com/mgonto/restangular/issues/337 but it seems to have not been fixed in all cases.

**Comment by RichardBradley** [comment]
Actually, I think the bug I am experiencing is in `ng-admin`, sorry.
