### ISSUE TITLE
json with key "ids" is problematic?

### ISSUE THREAD

**Issue by eikaramba** [mgonto/restangular#374]
Now to be honest i'm a little bit confused, but when i do a call with

```
scope.myobj.post("merge", {"ids":"test"});
```

there is only an empty {} json object in the request body.

However if i change ids to something else, e.g.

```
scope.myobj.post("merge", {"ids2":"test"});
```

it works. I cleared browser cache and the myobj object is perfectly fine(every other request works, e.g. delete, put, get etc.).

I don't think it is a restangular issue, but what could it be?

**Comment by ngehlert** [comment]
Just for future visitors that encouter the same problem.

The problem is in the line 1150 in the elemFunction method.
> if (_.isObject(callObj) && config.isRestangularized(callObj)) {
>           callObj = stripRestangular(callObj);
>         }

If your object is already an Restangular object the stripRestangular function will be called. This function removes all Restangular properties from the object.
The ids field is treated as Restangular field even if it is not in some cases.
AFAIK there is a different treatment for the id property and an internal elementId property so you can actually send an id property in the body.
Maybe this behavior needs to be implemented as well for ids? @mgonto 

A workaround for this problem is to use the customPut and use a non-Restangularized object to prevent the stripping.
So instead of

> restangularizedObject.put()

do

> Restangular.one(resourcePath, id).customPUT(normalObjectWithData)

Same goes for POST as well

**Comment by ngehlert** [comment]
does it make sense to reopen this task? @mgonto @pauldijou @bostrom

**Comment by bostrom** [comment]
I wrote a test according to the OP's description:

```
it('should accept "ids" as a key in POST data', function () {
      // https://github.com/mgonto/restangular/issues/374
      $httpBackend.expectPOST('/test/1/merge', {'ids': 'test'}).respond(200);
      var obj = Restangular.restangularizeElement(null, {id: 1}, 'test', true);
      obj.post('merge', {'ids': 'test'});
      $httpBackend.flush();
});
```
That one succeeds cleanly, meaning that doing a post with a non-restangularized element works fine, i.e. `obj.post('merge', {'ids': 'test'});` like the issue states. 

The problem occurs when posting a restangularized element, as in this test:

```
it('should accept "ids" as a key in POST data when using a restangularized element', function () {
      // https://github.com/mgonto/restangular/issues/374
      $httpBackend.expectPOST('/accounts/1/merge', {'ids': 'test'}).respond(200);
      var parent = Restangular.restangularizeElement(null, {id: 1}, 'accounts', true);
      var child = Restangular.restangularizeElement(null, {ids: 'test'}, null, false);
      parent.post('merge', child);
      $httpBackend.flush();
});
```

And this line gets executed (in `stripRestangular`): 
`return _.omit(elem, _.values(_.omit(config.restangularFields, 'id')));`

This removes all restangularize's own properties from the element, except `id`. I.e. Restangular assumes that your object doesn't "own" any of the properties in [`config.restangularFields`](https://github.com/mgonto/restangular/blob/master/src/restangular.js#L174), among which `ids` is one. 

As I understand it, the `ids` property is to collections what `id` is to elements, so in that regard it would make sense to treat it similarly to `id` in the `_.omit` call above. 

I'll see what I can do to fix this. 

As a workaround you can de-restangularize your child element and re-add the ids property before posting:

```
      var parent = Restangular.restangularizeElement(null, {id: 1}, 'accounts', true);
      var child = Restangular.restangularizeElement(null, {ids: 'test'}, null, false);
      var plainChild = _.assign({ids: child.ids}, child.plain());
      parent.post('merge', plainChild);
```

**Comment by bostrom** [comment]
Thinking about this a little closer, I'm trying to understand the user case here. Let's make some assumptions:

1. You have an object with a property `ids`, which in itself is a string and the object is an element and not a collection? 
2. Is the `ids` property an alias for `id`, i.e. is it supposed to be the element's identifier?  
I guess **not** since you expect the `ids` property to be found in the body and not in the URL when POSTing. 
3. Is the element a collection in which case the `ids` property should be an array and not a string?  
I guess **not** since it's not an array in the example.

Supposing that these assumptions are correct, you expect one of Restangular's "reserved" properties to be overwritable by you and passed on through the `stripRestangular` method. You would run into the same problem trying to have a property called, for example, `options` or `clone` in your element that you're POSTing. These would also be stripped out. 

Right now I don't see a reason to change the implementation of `stripRestangular` as the `ids` property can be seen as any other "reserved" property. Consider instead the other possible solutions:

1. Replacing the `ids` property with a non-reserved property, e.g. `_ids`
2. Stripping the restangularized element manually and re-adding the `ids` property to the plain element
3. Configuring Restangular to change the reserved `ids` property's value to something else than "ids", in which case it won't be stripped out.  
```
      $httpBackend.expectPOST('/accounts/1/merge', {'ids': 'test'}).respond(200);
      Restangular.setRestangularFields({
        ids: '_ids'
      });
      var parent = Restangular.restangularizeElement(null, {id: 1}, 'accounts', true);
      var child = Restangular.restangularizeElement(null, {ids: 'test'}, null, false);
      parent.post('merge', child);
      $httpBackend.flush();
```
Option 3 is probably the most attractive in this case.

**Comment by eikaramba** [comment]
quite some time passed since this use case but i remember it was that we have an api endpoint "merge" who accepts a list of ids which should be merged. think of different entities (e.g. companies) where there is a gui to merge companies which are all the same. Now our endpoint is given these ids and is merging them into one single entity, deleting the others. As your questions, i think assumption 3 is correct so sry for not elaborating the example good enough.

**Comment by bostrom** [comment]
Ok, in that case I think the current implementation is enough since it's easy to change the Restangular's built in `ids` property to something else.

**Comment by ngehlert** [comment]
could you provide an example of how to achieve this? also is this globaly possible or only per request?
in my use case i have a business object that can have relations/linked items via id, thus the request body has to contain an ids property that is an array. Since it is an external API renaming the property is not an option...

**Comment by bostrom** [comment]
@ngehlert as in the spec snippet above:

```javascript
      Restangular.setRestangularFields({
        ids: '_ids' // set this to anything else then "ids"
      });
```
Now restangular will use a property called `_ids` on each restangularized object instead of the default `ids`, which is clashing with your object's property. 

The documentation is a bit behind on this matter, I'll try to update it with some better info.

**Comment by ngehlert** [comment]
@bostrom awesome thanks :D well yeah it is actually quite easy then 👍
