### ISSUE TITLE
Restangular.copy causing the route in the object to become 'undefined'

### ISSUE THREAD

**Issue by mohuk** [mgonto/restangular#769]
Hey guys

I am trying to make a PUT request by copying the original restangular object, editing its properties and calling put.

But when I do a restangular.copy, it does not make a correct copy of the original. I was able to figure out that it sets the 'route' property to undefined.

See the fiddle below, it demonstrates the copy behavior.

http://jsfiddle.net/uma1rkhan/HB7LU/4678/

I dont know if this is correct or not but I am not able to make a successful PUT request with the copied object.

thanks :)

**Comment by philippeluickx** [comment]
+1, reqParams is also undefined after copy. Maybe other stuff too...

**Comment by rnybergh** [comment]
+1, Restangular.copy() on a collection breaks the collection. If I do a collectionName.post(newObj) after the copy(), there is an extra "/[object%20Object]" added to the route

**Comment by rnybergh** [comment]
+1

**Comment by akaNightmare** [comment]
+1

**Comment by daviesgeek** [comment]
Yup this is definitely broken. Confirmed with the latest version of Restangular:

http://plnkr.co/edit/zDuP4zWH6fD4ATSxPb03?p=preview

If someone wants to track this down and submit a PR, that would be awesome.

**Comment by mohuk** [comment]
It's been a while.

**Comment by rafialikhan** [comment]
Is this closed because its resolved? I get the same issue using restangular 1.5.2, where the copy is not done properly. I followed the plunker example. (http://plnkr.co/edit/d6yDka?p=preview)

` {
  "_id":{
    "$oid":"57f2a51ebd966f4fb6b51548"
  },
  "name":"Sample 2",
  "description":"asdas so this is important and its using schema form.",
  "site":"http://www.google.com",
  "route":"projects",
  "reqParams":{
    "apiKey":"4f847ad3e4b08a2eed5f3b54"
  },
  "restangularized":true,
  "fromServer":true,
  "parentResource":null,
  "restangularCollection":false
}`

`{
  "_id":{
    "$oid":"57f2a51ebd966f4fb6b51548"
  },
  "name":"Sample 2",
  "description":"asdas so this is important and its using schema form.",
  "site":"http://www.google.com",
  "route":"projects",
  "reqParams":null,
  "restangularized":true,
  "fromServer":true,
  "parentResource":null,
  "restangularCollection":false
}
`

**Comment by ap1969** [comment]
Hi,
Still happening on 1.6.1

http://plnkr.co/edit/gwSsimaEDmC6IJHorcNA?p=preview

Regards,
Andy
