### ISSUE TITLE
Sending an access token with every request

### ISSUE THREAD

**Issue by baptadn** [mgonto/restangular#81]
What's the best way for sending an access_token each time I perform an API call ? I tried to use the `setDefaultRequestParams` method but at the configuration step I dont know the value of the user'access token ... Any idea ?

Thanks

**Comment by wassimsalib** [comment]
Hi @mgonto 

Thanks a lot for your support, I have the same issue, that I want to add the token after the user logins and then use this authenticated restangular through the whole app, but my question is what is the difference between those 2 solutions:

```javascript
angular.module('mine').factory('LoggedInRestangular', function(Restangular) {
  var service = {};
  var instance = null;
  service.init = function(token) {
    instance = Restangular.withConfig(....)
  }

  service.get = function() {
    return instance;
  }

  return service;
});
```
and
```javascript
app.factory('LoggedInRestangular', ['$localStorage', 'Restangular', function ($localStorage, Restangular) {
        return Restangular.withConfig(function (RestangularConfigurer) {
            RestangularConfigurer.setDefaultHeaders({ "access_token": $localStorage.token || '' });
        });
    }]);
```

Because I store the token in $localstorage right after a successful login in my userCtrl, but I didn't know how to instantiate  LoggedInRestangular if I did it in the first way because the service.init takes argument "token".
