### ISSUE TITLE
setErrorInterceptor returns a status of 0 when setBaseUrl is also used

### ISSUE THREAD

**Issue by psmontoto** [mgonto/restangular#904]
Hi,

I'm new to restangular and I'm having a problem with setErrorInterceptor. If I create a simple error interceptor like the following:

app.run(function (Restangular) {
	Restangular.setErrorInterceptor(function(response) {
		alert('in ErrorInterceptor: status = ' + response.status);
	});
});

it displays the proper status UNLESS I also use setBaseUrl method:

app.config(function (RestangularProvider) {
  RestangularProvider.setBaseUrl('http://localhost:3000/api');
});

in which case the status is always '0'.

I'm not sure what I'm doing wrong. If I comment out the call to setBaseUrl, the correct status is displayed, but if I put that line of code back in, then the status is '0'.

Any help would be appreciated!

**Comment by sheoak** [comment]
I did a jsfiddle to reproduce the problem:

http://jsfiddle.net/sheoak/kvcqgL4f/2/

**Comment by kevgliss** [comment]
I am also having this issue...

**Comment by grabbou** [comment]
@sheoak in your example I am only getting `A server with the specified hostname could not be found.`. As it cannot be even resolved (domain does not exists), status code is not being assigned by the browser. Otherwise you get 404, as you are pointing to the domain you are running on and this domain exists but the route does not (which is obvious because JSFiddle does not provide `accounts` endpoint). 

In order to have this issue solved, please provide logs from developer console or from network tab where you have the full request/response statuses assigned by the browser.

**Comment by kevgliss** [comment]
@grabbou I have created a gist where I am experiencing the same issue but is a bit different from @sheoak jsfiddle.

https://gist.github.com/kevgliss/2c58230eae63aa81fd22

My server is sending a 500 response but it seems that restangular is having trouble getting it. 

Let me know if you need additional information.

**Comment by grabbou** [comment]
>  XMLHttpRequest cannot load http://127.0.0.1:5000/api/1/schedules. No 'Access-Control-Allow-Origin' header is present on the requested resource

@kevgliss as per $http spec, it will fail with status code 0 in case CORS is not enabled.

**Comment by sheoak** [comment]
@grabbou indeed, I need to create a specific page that does exists for the test, but the error should be indentical. I will try to updating the jsfiddle soon.

**Comment by grabbou** [comment]
Ok, let me know in a comment and we will see what's going on up there.
