### ISSUE TITLE
getRestangularUrl and getRequestedUrl returning erroneous URL after GET

### ISSUE THREAD

**Issue by simonbreak** [mgonto/restangular#906]
When getting a singular resource, the correct URL is built, but the returned element's `getRestangularUrl` and `getRequestedUrl` return the url with a spurious "/1" added to the end of it. In other words:

```
console.log(Restangular.one('thing').getRestangularUrl()); // prints "/thing"
Restangular.one('thing').get().then(function (thing) {
  console.log(thing.getRestangularUrl()); // prints "/thing/1"
});
```

**Comment by grabbou** [comment]
Side note -> @hitex 

```js
Restangular.all('user').get(id)
```
or
```js
Restangular.one('user, id).get()
```

Calling one with wrong signature will throw an error as it was never a correct usage and it's been producing various undefined bugs in route path from time to time.

**Comment by grabbou** [comment]
I am not sure if that's an issue. This is standard behaviour as "one" is meant to work with single objects, typically when they are available as sub endpoints of list endpoint. 

Following @hitex REST api answer, if you request with one() and your API response returns an ID, it's automatically added to the object, because when you do 

```js
collection.post(element)
/ POST users
```
you would expect to receive an object `user` that when called with `save` like below:
```js
user.save()
```
would invoke `/users/:id`.

**Comment by jondthompson** [comment]
But the original URL is how you get to the 'one'. In my instance, I'm asking the api for the current user by going to api/service/user.  Adding /1 to the end isn't appropriate, which is why it isn't in the url that I specify.
