### ISSUE TITLE
Is there a way to treat API query alias as not nested to make extendModel work?

### ISSUE THREAD

**Issue by alejoromano** [mgonto/restangular#961]
Hello,

I'm using `extendModel()` to add a function to my `api/products` endpoint. This function returns extra data coming from the logged in user.
I have this `baseProducts = Restangular.all('products');` restangular object for this endpoint 
I also have a query filter for featured products working as `api/products?featured=true`
If I do `baseProducts.getList({"featured": true});` the model is extendend and the function works perfectly.

Now my question begins here,
I would like to have my query filter work with an API alias as `api/products/featured`
yet when I try to do the following `baseProducts.all('featured').getList();` or `baseProducts.customGET('featured');`
I get the featured products, though the function added through`extendModel()` is not there. I'm not sure, but it seems this is because *featured* is treated as a nested entity instead of a parameter filtered query

Is there any correct way to do this?
Thanks in advance

**Comment by felixSchl** [comment]
Has this been resolved? Is there a way to achieve this?

**Comment by noahjcz** [comment]
I have this exact problem as well.

It's a problem for extendModel, and also when crudding with an alias.
as in I want...
PUT api/products/123abc

but because of the featured thing, it goes to...

PUT api/products/featured/123abc

ideally there would be something like: 


Restangular.all('products').alias('featured').getList()

Which would tell restangular that the model is "products", and that is also the base from which to send future CRUD.

**Comment by noahjcz** [comment]
looks like customGETLIST allows this functionality

**Comment by daviesgeek** [comment]
@alejoromano Does customGETLIST work for you?

**Comment by alejoromano** [comment]
@daviesgeek haven't tried it sorry, maybe @nkingsley mas more information

**Comment by daviesgeek** [comment]
Okay I'll close this then. Feel free to re-open if it's still an issue!
